version: "3.9"
services:
    person-api:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "G123456g"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports:
         - "1433:1433"

