//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonDirectory.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonDirectory.Application.Resources.ErrorTexts", typeof(ErrorTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაბადების თარიღის შევსება აუცილებელია..
        /// </summary>
        internal static string BirthDateRequired {
            get {
                return ResourceManager.GetString("BirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი აუცილებელი ველია..
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უნდა შეიცავდეს მხოლოდ ქართულ ან მხოლოდ ლათინურ ასოებს..
        /// </summary>
        internal static string NameOnlyGeorgianLatin {
            get {
                return ResourceManager.GetString("NameOnlyGeorgianLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი აუცილებელი ველია..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სიმბოლოების მაქსიმალური რაოდენობა არ უნდა აღემატებოდეს 50..
        /// </summary>
        internal static string NameSymbolMaxCount {
            get {
                return ResourceManager.GetString("NameSymbolMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სიმბოლოების მინიმალური რაოდენობა უნდა იყოს 2..
        /// </summary>
        internal static string NameSymbolMinCount {
            get {
                return ResourceManager.GetString("NameSymbolMinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფიზიკური პირი უნდა იყოს მინიმუმ 18 წლის..
        /// </summary>
        internal static string PersonAgeMustBeGreater18 {
            get {
                return ResourceManager.GetString("PersonAgeMustBeGreater18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი უნდა შეიცავდეს 11 სიმბოლოს..
        /// </summary>
        internal static string PrivateNumberLength {
            get {
                return ResourceManager.GetString("PrivateNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი უნდა შედგებოდეს მხოლოდ ციფრებისაგან..
        /// </summary>
        internal static string PrivateNumberOnlyIntegers {
            get {
                return ResourceManager.GetString("PrivateNumberOnlyIntegers", resourceCulture);
            }
        }
    }
}
